---
- hosts: "{{ hostname|default('test') }}"
  become: yes
  vars_files:
    - vars/default.yml
  roles:
    - common
    - nginx
    - php74
    - composer
    - mysql8
    - redis
    - certbot
    - ufw
    - node
    - fail2ban
    - postfix
