---
- name: import db
  mysql_db:
  name: "{{ item }}"
  state: import
  target: /tmp/{{ item }}.sql
  with_items:
  - "{{ project[project_name].dbname }}"

#- name: restart nginx
#  command: docker restart "nginx-proxy"
#
#- name: restart mysql
#  service:
#    name: mysql
#    enabled: yes
#    state: restarted
