---
- file:
    path: "{{ project_path }}"
    state: directory

- action: stat path="{{ project_path }}/docker-compose.yml"
  register: target_docker_compose

- name: Docker-compose state
  shell: /usr/local/bin/docker-compose ps
  register: compose_state   
  args:
    chdir: "{{ project_path }}"
  when: target_docker_compose.stat.exists

- name: Docker-compose down command
  shell: /usr/local/bin/docker-compose down
  args:
    chdir: "{{ project_path }}"
  when: ('compose_state.stdout_lines' != "" and target_docker_compose.stat.exists)

- name: Remove remote sources folder
  file:
    dest: "{{ project_path }}"
    state: absent

